dashboard/apps/urls.py
from django.urls import path
from django.urls.conf import include

from dashboard.apps.frontend.views import IndexView

app_name = 'app'

urlpatterns = [
    path('', 				IndexView.as_view(),						name='index'),

    path('pages/',			include('dashboard.apps.pages.urls')),
    path('components/',		include('dashboard.apps.components.urls')),
    path('utilities/',		include('dashboard.apps.utilities.urls')),
]

dashboard/urls.py
from django.contrib import admin

from django.urls import path
from django.urls.conf import include

app_name = 'main'

urlpatterns = [
    path('', 		include('dashboard.apps.urls')),
    path('admin/',	admin.site.urls),
]

dashboard/apps/pages/pagenotfound/models.py
from django.db import models

# Create your models here.

dashboard/apps/pages/pagenotfound/views.py
from django.shortcuts import render
from django.views import generic

from dashboard.apps.core.utils import log


class IndexView(generic.TemplateView):
    """
    IndexView:
    """
    module = 'IndexView'
    template_name = 'pagenotfound/base.html'

dashboard/apps/pages/pagenotfound/templates/pagenotfound/base.html
{% extends 'site/base.html' %}
{% load static %}

{% block title %} Dashboard: with Django and Bootstrap {% endblock title %}

{% block content %}
<div class="container-fluid">
	<div class="text-center">
		<div class="error mx-auto" data-text="404">404</div>
		<p class="lead text-gray-800 mb-5">Page Not Found</p>
		<p class="text-gray-500 mb-0">It looks like you found a glitch in the matrix...</p>

		<a href="{% url 'app:index' %}">&larr; Back to Dashboard</a>
	</div>
</div>
{% endblock content %}